### PR TITLE
#7: Fix iteration breakdown, add frequency analysis, and plot dropped nodes

### LINKED ISSUE #7: Fix iteration breakdown and analysis
Fix the index variable in line 103 of `slow_node.cc` and resolve subsequent issues with the analysis script:

```
File "detect_slow_nodes.py", line 632, in detect
    for r_id, (iter, t) in self.__slow_iterations.items():
              ^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```

### LINKED ISSUE #8: Read/write CPU freq and sensors before and after benchmark
- Add functions to read/write the CPU frequency with `cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq`~~`| sort | uniq -c`~~
- Save the CPU freq to same file as sensors output
- Write one file (with both sensors and cpu freq info) before the benchmark
- Write the file again (with updated readings) after the benchmark

### PR DESCRIPTION
**Pull request by cwschilly**
Fixes #7 
Fixes #8 

Also refactors the Python code to be more modular and adds both function timers and a new plot for dropped nodes.

The plot the dropped nodes for previous runs, run from the project dir:

```
python detection/plot_dropped_nodes.py -s slownode.log -a slownodenanalysis.log -o /path/to/output_dir
```

Where:

```
-s <slownode.log>         - The driver output (from slow_node.cc)
-a <slownodeanalysis.log> - The analysis output (from detect_slow_nodes.py)
```

### CODE REVIEW

**Comment by cwschilly** [comment]
@nlslatt @lifflander Should we ignore the first iteration during analysis?

**Comment by nlslatt** [comment]
> @nlslatt @lifflander Should we ignore the first iteration during analysis?

We should probably do one more than the requested number of iterations and completely throw out the first one. I think the first iteration should not be printed or added to the total time.

**Comment by nlslatt** [comment]
@cwschilly Are you planning to fix the sensors node name problem as a separate PR or part of this? There are a lot of things that need to be addressed before I can start collecting new data and I'd really like to start collecting it now.

**Comment by nlslatt** [comment]
It would be helpful if the list of slowest iterations included the iteration number and not just the time.

**Comment by cwschilly** [comment]
> @cwschilly Are you planning to fix the sensors node name problem as a separate PR or part of this? There are a lot of things that need to be addressed before I can start collecting new data and I'd really like to start collecting it now.

@nlslatt I can put everything in this PR. Going to try to get everything fixed up by the end of the day--I'll ping you when it's ready

**Comment by nlslatt** [comment]
@cwschilly Jonathan had asked me for the barrier after the random initialization (i.e., before the for loop within `runBenchmark`), which is where I've been using one

File: src/slow_node.cc [hunk 1]
```diff
@@ -22,13 +22,17 @@ std::tuple<std::vector<double>, double> runBenchmark() {
...
   double total_time = 0.0;
 
+  MPI_Barrier(MPI_COMM_WORLD);
+
   for (int i = 0; i < iters; i++) {
     Kokkos::Timer timer;
     KokkosBlas::gemm("N", "N", 1.0, A, B, 0.0, C);
     Kokkos::fence();
     double time = timer.seconds();
     total_time += time;
```
Comment (nlslatt) [inline src/slow_node.cc]: You missed not including the first iteration in the total time.

Comment (cwschilly) [reply src/slow_node.cc]: Fixed this, thanks

**Comment by nlslatt** [comment]
@cwschilly The node names in the sensors files are still incorrect. All nodes have been given the name of the first node in the allocation.

File: src/freq.cc [hunk 2]
```diff
@@ -2,30 +2,36 @@
...
 namespace freq {
 
-std::vector<int> readCPUFrequencies() {
-    std::vector<int> freqs;
-    FILE* pipe = popen("cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq", "r");
-    if (!pipe) {
-        std::cerr << "Warning: Could not read CPU frequencies." << std::endl;
-        return freqs;
+int readCPUFrequency() {
+    int cpu = sched_getcpu();
```
Comment (nlslatt) [inline src/freq.cc:12]: Shouldn't we start using this for the temperatures too rather than assuming that they are being matched up correctly?

Comment (cwschilly) [reply src/freq.cc:12]: `sched_getcpu()` gives the logical core, which corresponds to the frequency files in `/sys/devices/system/cpu/cpuX`.

`sensors` uses the physical core numbering, which doesn't match up with the logical IDs

Comment (nlslatt) [reply src/freq.cc:12]: Why did you switch to using `sched_getcpu()` then? What is wrong with just doing a series of fopens in numerical order on the leader rank of each node?

Comment (cwschilly) [reply src/freq.cc:12]: `sched_getcpu()` guarantees that we're reading the current core's frequency right when it gets to `readCPUFrequency()`. If I do a series of `fopen`s on the node leader, then there could be more time in between the benchmark running on a core and getting the frequency reading for that core.

(The previous approach was to read every CPU frequency for all cores on every rank, and then max-reduce like we do with the temperatures to only save the highest frequency on every core, on each node, etc. I thought this new approach was a little more precise)

That being said, the time delay may only be relevant for the `sensors` output; I'm not sure how much the frequency would change in the moments after running the benchmark.

Comment (lifflander) [reply src/freq.cc:12]: I think this approach makes sense (to avoid opening lots of files) and reading `scaling_cur_freq` is the right file to read to get the frequency.

File: detection/plot_slow_nodes.py [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+
+def main():
+    """
+    See documentation of SlowNodeDetector class, as well as
+    the detect() and createHostfile() methods, for more information.
+    """
+    parser = argparse.ArgumentParser(description='Slow Rank Detector script.')
+    parser.add_argument('-s', '--slownode', help='Absolute or relative path to the output from slow_node executable', required=True)
+    parser.add_argument('-a', '--analysis', help='Absolute or relative path to the output from detect_slow_nodes', required=True)
+    parser.add_argument('-o', '--output', help='Absolute or relative path to the output from detect_slow_nodes', default=None)
```
Comment (nlslatt) [inline detection/plot_slow_nodes.py]: The help needs to distinguish between the original output (to be used as input) and the new output.

Comment (nlslatt) [reply detection/plot_slow_nodes.py]: Is the new output a directory for the plot? That's not clear above.

Comment (cwschilly) [reply detection/plot_slow_nodes.py]: Fixed, sorry about that. `-o` is the path to where you want to save the plot.

**Review by lifflander — APPROVED** [review]

**Comment by nlslatt** [comment]
I think the node names are working correctly now.
